###
GET  http://localhost:8080/api/reservations/

> {%
 client.test("Request executed successfully", function() {
 client.assert(response.status === 200, "Response status is not 200");
 });
 %}

###
POST http://localhost:8080/api/reservations/
Content-Type: application/json

{
  "reservationName" : "Selci Haarschnitt",
  "customerKey" : "4sYu"
}

###

POST http://localhost:8080/api/reservations/
Content-Type: application/json

{
  "reservationName" : "SBT Haarschnitt",
  "customerKey" : "fLTk"
}

###
GET  http://localhost:8080/api/reservations/9es2N

###
//PATCH  http://localhost:8080/api/reservations/Selci%20Haarschnitt?reservationName=SBT-Haarschnitt
PATCH  http://localhost:8080/api/reservations/9es2N?reservationName=SBT-Haarschnitt

###
GET  http://localhost:8080/api/reservations/Wapzt

> {%
 client.test("Request executed successfully", function() {
 client.assert(response.status === 200, "Response status is not 200");
 });
 %}

###
